Repository ioBroker/ioBroker.js-controller, pull requests merged in 2019-03, with the labels that each got.

#347 Fix some issues found by LGTM.com
  lib/adapter.js
  lib/cli/cliLogs.js
  lib/cli/cliProcess.js
  lib/logger.js
  lib/objects/objectsInMemServer.js
  lib/objects/objectsUtils.js
  lib/states/statesInRedis.js
Labels: Code Police :policeman:

#356 Fix missing this reference in cliHost.js
  lib/cli/cliHost.js
Labels: bug

#353 fixes #352, add monitoring for event-Loop-Lag
  lib/adapter.js
  lib/setup/setupInstall.js
  lib/tools.js
  main.js
Labels: enhancement
